name: Build and Deploy
on:
  push:
  #schedule:
  #  - cron: '0 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run gen ${{ secrets.GH_ACCESS_USERNAME }} ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: out # The branch the action should deploy to.
          folder: .build # The folder the action should deploy.
